config/routes.rb
Rails.application.routes.draw do

  root      'static#home'

  get       'how_it_works'  =>    'static#how'
  get       'showcase'      =>    'static#showcase'
  get       'signup'        =>    'users#new'
  get       'signin'        =>    'sessions#new'
  get       'search',       to:   'search#search'

  get       '/404'          =>    'errors#not_found'
  get       '/422'          =>    'errors#unprocessable'
  get       '/500'          =>    'errors#server_error'


  resources :activities,        only:   :index
  resources :invitations,       only:   [:new, :create]
  resources :password_resets,   only:   [:new, :create, :edit, :update]
  resources :relationships do
    get 'pending', on: :collection
  end
  resources :search,            only:   :index
  resource  :session
  resources :stories
  resources :storybooks
  resources :users,             only:   [:show, :new, :create, :edit, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/storybook.rb
# == Schema Information
#
# Table name: storybooks
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             default("")
#  cover        :string
#  published    :boolean          default(FALSE)
#  published_on :date
#  user_id      :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Storybook < ActiveRecord::Base

  include             PgSearch
  include             Trackable

  mount_uploader      :cover,       ImageUploader

  multisearchable     against:      [:title, :description]

  belongs_to          :user
  has_many            :chapters,      dependent: :destroy
  has_many            :stories,       through: :chapters

  validates           :cover,       format: { with: /\w+.(gif|jpg|png)\z/i, allow_blank: true }
  validates           :title,       presence: true
  validates           :user_id,     presence: true

  after_create        :track_activity

end

app/controllers/storybooks_controller.rb
class StorybooksController < ApplicationController

  before_action     :require_signin
  before_action     :set_correct_user
  before_action     :set_storybook,         only:   [:show,   :edit, :update, :destroy]

  def index
    @page_title = 'My storybooks'
    @storybooks = @user.storybooks.page params[:page]

    respond_to do |format|
      format.html
      format.json { render json: @storybooks, status: :ok }
    end
  end

  def show
    @page_title = "Showing: #{@storybook.title}"

    respond_to do |format|
      format.html
      format.json { render json: @storybook, status: :ok }
    end
  end

  def new
    @page_title = 'Start a storybook'
    @storybook = @user.storybooks.new
  end

  def create
    @storybook = @user.storybooks.new(storybook_params)

    if @storybook.save
      redirect_to @storybook, success: 'Your storybook was successfully created!'
    else
      flash.now[:danger] = 'There was a problem creating your storybook.  Please try again.'
      render  :new
    end
  end

  def edit
    @page_title = "Editing #{@storybook.title}"
  end

  def update
    if @storybook.update(storybook_params)
      redirect_to @storybook, success: 'Your storybook was updated.'
    else
      flash.now[:danger] = 'There was a problem updating your storybook.  Please try again.'
      render :edit
    end
  end

  def destroy
    @storybook.destroy

    flash[:warning] = 'Your storybook was successfully removed.'

    redirect_to storybooks_url
  end

  def search
    @storybooks = Storybook.search(params[:query]).records
  end

  private

    def set_correct_user
      @user = current_user

      redirect_to :back unless current_user?(@user)
    end

    def set_storybook
      @storybook = Storybook.find(params[:id])

      redirect_to @user unless @storybook.user == current_user
    end

    def storybook_params
      params.require(:storybook).permit(:title, :description, :cover, story_ids: [])
    end

end

app/helpers/storybooks_helper.rb
module StorybooksHelper

  def image_for(storybook)
    storybook.cover.blank? ? 'default_cover_s5czvu.jpg' : storybook.cover_url
  end

  def render_published_status(storybook)
    storybook.published? ? 'Published' : 'Not published'
  end

end

app/views/storybooks/_storybook.erb
<%= link_to storybook, class:'list-group-item row' do %>

    <div class="col-lg-6">

      <%= content_tag :h4, storybook.title, class:'list-group-item-heading' %>

      <%= content_tag :p, truncate(storybook.description, length: 125), class:'list-group-item-text' %>

    </div>

    <div class="col-lg-3">

      <%= render_published_status(storybook) %>

    </div>

    <div class="col-lg-3 text-muted">

      Started <%= time_ago_in_words(storybook.created_at) %> ago

    </div>

<% end %>

app/views/storybooks/_sub_nav.erb
<% unless current_page?(storybooks_path) %>

    <%= content_tag :li, link_to(icon('angle-double-left', 'Return to my storybooks'), storybooks_path, class:'navbar-link') %>

<% end %>

<% if current_page?(storybooks_path) %>

    <%= content_tag :li, link_to('Start a new storybook', new_storybook_path, class:'navbar-link') %>

<% end %>

<%= yield :sub_nav_content %>

app/views/storybooks/edit.html.erb
<%= content_for :sub_nav_content do %>

    <%= content_tag :li, link_to('Publish this storybook', "#", class:'navbar-link')%>

    <%= content_tag :li, link_to('Delete this storybook', @storybook, method: :delete,
                                 data: { confirm: 'you want to delete this storybook?' },
                                 class:'navbar-link')%>

<% end %>

<%= form_for @storybook, html: { class:'form-storybook' } do |f| %>

    <div class="form-group">
      <%= f.label :title, class:'control-label h5 text-primary font-thin' %>
      <%= f.text_field :title, class:'form-control', autofocus:true %>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-2">
          <%= cl_image_tag image_for(@storybook), size: '156x206', class:'img-responsive' %>
        </div>
        <div class="col-lg-10">
          <%= f.label :cover, class:'control-label h5 text-primary font-thin' %>
          <%= f.hidden_field  :cover_cache %>
          <%= f.file_field :cover, class:'form-control' %>
          <p class="help-block">Upload a photo to change your storybook cover.</p>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class:'control-label h5 text-primary font-thin' %>
      <%= f.text_area :description, class:'form-control', rows:4 %>
    </div>

    <h5 class="text-primary font-thin">Included stories</h5>
    <%= f.collection_check_boxes :story_ids, @user.stories, :id, :title do |b| %>
        <div class="checkbox">
          <%= b.label do %>
              <%= b.check_box %>
              <%= link_to b.text, story_path(id: b.value), class:'text-muted', remote:true %>
          <% end %>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.submit 'Update my storybook', class:'btn btn-primary' %> or
        <%= link_to 'Cancel', @storybook %>
    </div>

<% end %>

<%= content_tag :div, nil, id: 'story-modal', class: 'modal fade', tabindex: -1, role: 'dialog' %>

app/views/storybooks/index.html.erb
<% if @storybooks.empty? %>

    <%= render partial: 'shared/nothing_to_render', locals: { item: 'storybook' } %>

<% else %>

    <div class="list-group m-t-lg">

        <% @storybooks.each do |storybook| %>

            <%= render storybook %>

        <% end %>

    <%= paginate @storybooks %>

    </div>

<% end %>

app/views/storybooks/new.html.erb
<%= bootstrap_form_for @storybook, html: { class:'form-storybook' } do |f| %>

    <h5 class="text-primary">Title</h5>
    <%= f.text_field :title, hide_label:true, placeholder:'Enter your title here', autofocus:true %>

    <h5 class="text-primary">Description</h5>
    <%= f.text_area :description, hide_label: true, rows:4, placeholder:'Write a short description' %>

    <%= f.form_group do %>
        <%= f.primary 'Create my storybook' %> or
        <%= link_to 'Cancel', storybooks_path %>
    <% end %>

<% end %>

app/views/storybooks/show.html.erb
<%= content_for :sub_nav_content do %>

    <%= content_tag :li, link_to('Edit this storybook', edit_storybook_path(@storybook), class:'navbar-link')%>

<% end %>

<div class="well">

    <div class="row">

      <div class="col-lg-2">

        <%= cl_image_tag image_for(@storybook), size: '156x206', class:'img-responsive' %>

      </div>

      <div class="col-lg-10">

        <%= content_tag :h4, "by #{@storybook.user.name}", class:'font-thin' %>

        <%= content_tag :p, sanitize(@storybook.description), class:'lead' %>

      </div>

    </div>

</div>

<h4 class="text-primary font-thin">Stories in this storybook:</h4>

<ul class="list-group">

  <% @storybook.stories.each do |story| %>

      <%= content_tag :li, link_to(story.title, story_path(story), remote:true), class:'list-group-item' %>

  <% end %>

</ul>

<%= content_tag :div, nil, id: 'story-modal', class: 'modal fade', tabindex: -1, role: 'dialog' %>