config/routes.rb
Rails.application.routes.draw do

  root      'static#home'

  get       'how_it_works'  =>    'static#how'
  get       'showcase'      =>    'static#showcase'
  get       'signup'        =>    'users#new'
  get       'signin'        =>    'sessions#new'
  get       'search',       to:   'search#search'

  get       '/404'          =>    'errors#not_found'
  get       '/422'          =>    'errors#unprocessable'
  get       '/500'          =>    'errors#server_error'


  resources :activities,        only:   :index
  resources :invitations,       only:   [:new, :create]
  resources :password_resets,   only:   [:new, :create, :edit, :update]
  resources :relationships do
    get 'pending', on: :collection
  end
  resources :search,            only:   :index
  resource  :session
  resources :stories
  resources :storybooks
  resources :users,             only:   [:show, :new, :create, :edit, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  reset_token     :string
#  reset_sent_at   :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  active          :boolean          default(FALSE)
#

class User < ActiveRecord::Base

  include             Account
  include             Authentication
  include             Family
  include             PasswordReset
  include             TokenGenerator
  include             Trackable

  to_param            :name

  has_many            :activities,    as: :owner
  has_many            :activities,    as: :recipient
  has_many            :stories,       dependent:      :destroy
  has_many            :storybooks,    dependent:      :destroy

  validates           :name,  :email, presence: true
  validates           :email, format: { with: /\A\S+@\S+\z/ }
  validates           :email, uniqueness: { case_sensitive: false }

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action     :walled_garden,         only:   [:new, :create]
  before_action     :require_signin,        except: [:new, :create]
  before_action     :require_correct_user,  except: [:new, :create]

  def show
    @page_title = @user.name

    get_user_vars
  end

  def new
    @token = params[:invitation_token]
    @user = User.new

    render layout: 'session'
  end

  def create
    @user = User.new(user_params)
    @token = params[:invitation_token]

    if @user.activate
      sign_in(@user)

      @user.create_relationship_from_invitation(@token) if @token

      redirect_to @user, success: 'Thanks for signing up!'
    else
      flash.now[:danger] = 'There was a problem with your registration.  Please try again.'

      render :new, layout: 'session'
    end
  end

  def edit
    @page_title = "Editing #{@user.name}"
  end

  def update
    if @user.update(user_params)
      redirect_to @user, success: 'Account successfully updated!'
    else
      flash.now[:warning] = 'There was a problem updating your account.  Please try again.'

      render :edit
    end
  end

  def destroy
    if @user.deactivate
      sign_out_user

      redirect_to root_url
    else
      flash.now[:danger] = 'You are not authorized to deactivate this account.'
      render :edit
    end
  end

  private

    def require_correct_user
      @user = User.find(params[:id])

      redirect_to user_url(current_user) unless current_user?(@user)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def get_user_vars
      @storybooks = @user.storybooks.order(created_at: :desc).limit(10)
      @stories = @user.stories.order(created_at: :desc).limit(10)
      @relatives = @user.relatives.order(created_at: :desc).limit(10)
      @activities = Activity.where(owner_id: @user.id).order(created_at: :desc).limit(10)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def profile_image_for(user, options={})
    size = options[:size] || 80
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
    image_tag url, alt: user.name
  end

  def storybooks_for(user)
    user.storybooks.pluck(:title).join(', ')
  end

  def stories_for(user)
    user.stories.pluck(:title).join(', ')
  end

end

app/views/users/_sub_nav.erb
<% if current_page?(user_path(current_user)) %>

    <%= content_tag :li, link_to('Start a new storybook', new_storybook_path) %>

    <%= content_tag :li, link_to('Write a new story', new_story_path) %>

    <%= content_tag :li, link_to('Invite a new family member', new_relationship_path) %>

<% end %>

<%= yield :sub_nav_content %>

app/views/users/_user_activities.erb
<div class="tab-pane fade" id="user-activities">

  <ul class="list-group">

    <% if @activities.any? %>

        <% @activities.each do |activity| %>

            <%= render_each(activity) %>

        <% end %>

        <%= content_tag :p, (link_to 'Vew all activities', activities_path), class:'lead m-t-lg' %>

    <% else %>

        <%= render partial: 'shared/nothing_to_render', locals: { item: 'activity' } %>

    <% end %>

  </ul>

</div>

app/views/users/_user_activity.erb
<div class="tab-pane fade" id="user-activity">

  <ul class="list-group">

    <% if @activities.any? %>

        <%= render_activity(@activities) %>

    <% else %>

        <%= render partial: 'shared/nothing_to_render', locals: { item: 'activity' } %>

    <% end %>

  </ul>

</div>

app/views/users/_user_relationships.erb
<div class="tab-pane fade" id="user-relatives">

  <ul class="list-group">

    <% if @relatives.any? %>

        <% @relatives.each do |relative| %>

            <%= render partial: 'relationships/relationship', locals: { item: relative, type: 'relative' } %>

        <% end %>

        <%= content_tag :p, (link_to 'Vew all family members', relationships_path), class:'lead m-t-lg' %>

    <% else %>

        <%= render partial: 'shared/nothing_to_render', locals: { item: 'relative' } %>

    <% end %>

  </ul>

</div>

app/views/users/_user_stories.erb
<div class="tab-pane fade in" id="user-stories">

  <ul class="list-group">

    <% if @stories.any? %>

        <% @stories.each do |story| %>

            <%= render story %>

        <% end %>

        <%= content_tag :p, (link_to 'Vew all stories', stories_path), class:'lead m-t-lg' %>

    <% else %>

        <%= render partial: 'shared/nothing_to_render', locals: { item: 'story' } %>

    <% end %>

  </ul>

</div>

app/views/users/_user_storybooks.erb
<div class="tab-pane fade active in" id="user-storybooks">

  <ul class="list-group">

    <% if @storybooks.any? %>

        <% @storybooks.each do |storybook| %>

            <%= render storybook %>

        <% end %>

        <%= content_tag :p, (link_to 'Vew all storybooks', storybooks_path), class:'lead m-t-lg' %>

     <% else %>

        <%= render partial: 'shared/nothing_to_render', locals: { item: 'storybook' } %>

     <% end %>

  </ul>

</div>

app/views/users/edit.html.erb
<%= bootstrap_form_for @user, html: { class:'form-user-edit' } do |f| %>

   <%= f.text_field :name, label_class:'text-warning', autofocus:true %>

   <%= f.email_field :email, label_class:'text-warning' %>

   <%= f.password_field :password %>

   <%= f.password_field :password_confirmation %>

   <%= f.form_group do %>
          <%= f.primary 'Update' %> or
          <%= link_to 'Cancel', @user %>
   <% end %>

<% end %>

<p>
  <%= link_to 'Deactivate my account', @user, method: :delete, class:'text-danger', data: { confirm: 'You want to deactivate your account?' } %>
</p>

app/views/users/new.html.erb
<%= bootstrap_form_for @user, html: { class:'form-signup'},
                       layout: :horizontal, label_col:'col-lg-3', control_col:'col-lg-9' do |f| %>

    <fieldset>

      <legend>Register for FamilyBook</legend>

      <% if @token %>
          <%= hidden_field_tag :invitation_token, @token %>
      <% end %>

      <%= f.text_field  :name, autofocus:true %>

      <%= f.email_field :email %>

      <%= f.password_field :password %>

      <%= f.password_field :password_confirmation, label:'Confirm password' %>

      <%= f.form_group do %>
          <%= f.primary 'Register' %> or
          <%= link_to 'Cancel', root_path %>
      <% end %>

    </fieldset>

    <p class="text-center">
      Already a member?  <%= link_to 'Sign in here', signin_path %>
    </p>

<% end %>


<%= @token %>

app/views/users/show.html.erb
<%= content_for :edit_profile do %>
    <% if current_user?(@user) %>
        <%= content_tag :span, link_to('(Edit)', edit_user_path(@user), class:'text-warning text-sm') %>
    <% end %>
<% end %>

<%= profile_image_for(@user) %>

<h4 class="font-thin m-t-xl">Recent items:</h4>

<ul class="nav nav-tabs">
  <li class="h5 active font-thin">
    <%= link_to '#user-storybooks', data: { toggle:'tab' } do %>
        Storybooks

        <%= content_tag :span, "#{@storybooks.size}", class:'badge' %>
    <% end %>
  </li>

  <li class="h5 font-thin">
    <%= link_to '#user-stories', data: { toggle:'tab' } do %>
        Stories

        <%= content_tag :span, "#{@stories.size}", class:'badge' %>
    <% end %>
  </li>

  <li class="h5 font-thin">
    <%= link_to '#user-relatives', data: { toggle:'tab' } do %>
        Family members

        <%= content_tag :span, "#{@relatives.size}", class:'badge' %>
    <% end %>
  </li>

  <li class="h5 font-thin">
    <%= link_to '#user-activities', data: { toggle:'tab' } do %>
        Activity

        <%= content_tag :span, "#{@activities.size}", class:'badge' %>
    <% end %>
  </li>
</ul>

<div class="tab-content">
  <%= render partial: 'user_storybooks' %>

  <%= render partial: 'user_stories' %>

  <%= render partial: 'user_relationships' %>

  <%= render partial: 'user_activities' %>
</div>

<%= content_tag :div, nil, id: 'story-modal', class: 'modal fade', tabindex: -1, role: 'dialog' %>