config/routes.rb
Rails.application.routes.draw do

  root      'static#home'

  get       'how_it_works'  =>    'static#how'
  get       'showcase'      =>    'static#showcase'
  get       'signup'        =>    'users#new'
  get       'signin'        =>    'sessions#new'
  get       'search',       to:   'search#search'

  get       '/404'          =>    'errors#not_found'
  get       '/422'          =>    'errors#unprocessable'
  get       '/500'          =>    'errors#server_error'


  resources :activities,        only:   :index
  resources :invitations,       only:   [:new, :create]
  resources :password_resets,   only:   [:new, :create, :edit, :update]
  resources :relationships do
    get 'pending', on: :collection
  end
  resources :search,            only:   :index
  resource  :session
  resources :stories
  resources :storybooks
  resources :users,             only:   [:show, :new, :create, :edit, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text             default("")
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Story < ActiveRecord::Base

  include             PgSearch
  include             Trackable

  multisearchable     against:        [:title, :content]

  belongs_to          :user
  has_many            :chapters,      dependent: :destroy
  has_many            :storybooks,    through: :chapters

  validates           :title,         presence: true
  validates           :user_id,       presence: true

  after_create        :track_activity

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_action     :require_signin
  before_action     :set_correct_user
  before_action     :set_correct_story,   only:   [:show, :edit, :update, :destroy]

  def index
    @page_title = 'My stories'
    @stories = @user.stories.page params[:page]
  end

  def show
    @page_title = "Showing: #{@story.title}"
    respond_to do |format|
      format.html
      format.js
      format.json { render json:  @story, status: :ok }
    end
  end

  def new
    @page_title = 'Write a story'
    @story = @user.stories.new
  end

  def create
    @story = @user.stories.new(story_params)
    if @story.save
      redirect_to @story, success: 'Your story was saved.'
    else
      flash.now[:danger] = 'There was a problem saving your story.  Please try again'
      render  :new
    end
  end

  def edit
    @page_title = "Editing #{@story.title}"
  end

  def update
    if @story.update(story_params)
      redirect_to @story, success: 'Your story was updated.'
    else
      flash.now[:danger] = 'There was a problem updating your story.  Please try again.'
      render :edit
    end
  end

  def destroy
    @story.destroy
    flash[:warning] = 'Your story was successfully removed.'
    redirect_to stories_url
  end

  private

    def set_correct_user
      @user = current_user
      redirect_to :back unless current_user?(@user)
    end

    def set_correct_story
      @story = Story.find(params[:id])
      redirect_to @user unless @story.user == current_user
    end

    def story_params
      params.require(:story).permit(:title, :content)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper

  def action_for(story)
    story.new_record? ? 'Save' : 'Update'
  end


end

app/views/stories/_form.erb
<%= bootstrap_form_for @story, html: { class:'form-story' } do |f| %>

    <h5 class="text-primary">Title</h5>
    <%= f.text_field :title, hide_label:true, placeholder:'Enter your title here', autofocus:true %>

    <h5 class="text-primary">Content</h5>
    <%= f.text_area :content, hide_label: true, rows:20, placeholder:'Write your story here.' %>

    <%= f.form_group do %>
        <%= f.primary "#{action_for(@story)} my story" %> or
        <%= link_to 'Cancel', stories_path %>
    <% end %>

<% end %>

app/views/stories/_modal.erb
<div class="modal-dialog modal-lg">

  <div class="modal-content">

    <div class="modal-header">
      <%= content_tag :button, 'x', class: 'close', data: { dismiss: 'modal' } %>
      <%= content_tag :h4, @story.title, class: 'font-thin modal-title' %>
      <%= content_tag :p, "by #{@story.user.name}", class:'font-thin' %>
    </div>

    <div class="modal-body">
      <%= content_tag :p, sanitize(@story.content) %>
    </div>

    <div class="modal-footer">
      <%= content_tag :button, 'Close', class: 'btn btn-primary', data: { dismiss: 'modal' } %>
    </div>

  </div>

</div>

app/views/stories/_story.erb
<li class="list-group-item row">

  <div class="col-lg-6">

    <%= link_to story.title, story %>

  </div>

  <div class="col-lg-3">

    Inclusions <%= content_tag :span, story.storybooks.count, class:'badge' %>

  </div>

  <div class="col-lg-3 text-muted">

    Written <%= time_ago_in_words(story.created_at) %> ago

  </div>



</li>

app/views/stories/_sub_nav.erb
<% unless current_page?(stories_path) %>

    <%= content_tag :li, link_to(icon('angle-double-left', 'Return to my stories'), stories_path, class:'navbar-link') %>

<% end %>

<% if current_page?(stories_path) %>

    <%= content_tag :li, link_to('Write a new story', new_story_path, class:'navbar-link') %>

<% end %>

<%= yield :sub_nav_content %>

app/views/stories/edit.html.erb
<%= content_for :sub_nav_content do %>

    <%= content_tag :li, link_to('Delete this story', @story, method: :delete, data: { confirm: 'you want to delete this story?' }) %>

<% end %>

<%= render 'form' %>

app/views/stories/index.html.erb
<% if @stories.empty? %>

    <%= render partial: 'shared/nothing_to_render', locals: { item: 'story' } %>

<% else %>

    <ul class="list-group m-t-lg">

        <% @stories.each do |story| %>

           <%= render story %>

        <% end %>

        <%= paginate @stories %>

    </ul>

<% end %>

app/views/stories/new.html.erb
<%= render 'form' %>

app/views/stories/show.html.erb
<%= content_for :sub_nav_content do %>

    <%= content_tag :li, link_to('Edit this story', edit_story_path(@story), class:'navbar-link')%>

<% end %>

<div class="well">

    <%= content_tag :h4, "by #{@story.user.name}", class:'font-thin' %>

    <%= content_tag :p, sanitize(@story.content), class:'lead' %>

</div>

app/views/stories/show.js.erb
$('#story-modal').html("<%= j render('stories/modal') %>")
$('#story-modal').modal('show')