config/routes.rb
Rails.application.routes.draw do

  root      'static#home'

  get       'how_it_works'  =>    'static#how'
  get       'showcase'      =>    'static#showcase'
  get       'signup'        =>    'users#new'
  get       'signin'        =>    'sessions#new'
  get       'search',       to:   'search#search'

  get       '/404'          =>    'errors#not_found'
  get       '/422'          =>    'errors#unprocessable'
  get       '/500'          =>    'errors#server_error'


  resources :activities,        only:   :index
  resources :invitations,       only:   [:new, :create]
  resources :password_resets,   only:   [:new, :create, :edit, :update]
  resources :relationships do
    get 'pending', on: :collection
  end
  resources :search,            only:   :index
  resource  :session
  resources :stories
  resources :storybooks
  resources :users,             only:   [:show, :new, :create, :edit, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id             :integer          not null, primary key
#  trackable_id   :integer
#  trackable_type :string
#  owner_id       :integer
#  owner_type     :string
#  recipient_id   :integer
#  recipient_type :string
#  key            :string
#  parameters     :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Activity < ActiveRecord::Base

  belongs_to :owner,      polymorphic: true
  belongs_to :recipient,  polymorphic: true
  belongs_to :trackable,  polymorphic: true

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action     :require_signin
  before_action     :set_correct_user

  def index
    @page_title = 'My activities'
    @activities = Activity.where(owner: @user).order(created_at: :desc).page params[:page]
  end

  private

    def set_correct_user
      @user = current_user
      redirect_to :back unless current_user?(@user)
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def render_each(activity)
    key = activity.key.split('.')[0]
    render partial: "activities/#{key}", locals: { activity: activity }
  end

end

app/views/activities/_story.erb
<li class="list-group-item row">

  <div class="col-lg-1">

    <%= icon 'pencil-square', nil, class:'text-primary fa-2x' %>

  </div>

  <div class="col-lg-8">

    <%= activity.owner.name %> wrote story

    <%= content_tag :span, link_to(activity.trackable.title, story_path(activity.trackable), remote:true) %>

  </div>

  <div class="col-lg-3">

    <%= content_tag :small, "#{time_ago_in_words(activity.created_at)} ago", class:'text-muted' %>

  </div>

</li>

app/views/activities/_storybook.erb
<li class="list-group-item row">

  <div class="col-lg-1">

    <%= icon 'book', nil, class:'text-primary fa-2x' %>

  </div>

  <div class="col-lg-8">

    <%= activity.owner.name %> created storybook

    <%= content_tag :span, link_to(activity.trackable.title, storybook_path(activity.trackable)) %>

  </div>

  <div class="col-lg-3">

    <%= content_tag :small, "#{time_ago_in_words(activity.created_at)} ago", class:'text-muted' %>

  </div>

</li>

app/views/activities/_user.erb
<li class="list-group-item row">

  <div class="col-lg-1">

    <%= icon 'user', nil, class:'text-primary fa-2x' %>

  </div>

  <div class="col-lg-8">

    <%= activity.owner.name %> became a member

  </div>

  <div class="col-lg-3">

    <%= content_tag :small, "#{time_ago_in_words(activity.created_at)} ago", class:'text-muted' %>

  </div>

</li>

app/views/activities/index.html.erb
<% if @activities.empty? %>

    <%= render partial: 'shared/nothing_to_render', locals: { item: 'activity' } %>

<% else %>

    <ul class="list-group">
        <% @activities.each do |activity| %>

           <%= render_each(activity) %>

      <% end %>
    </ul>

    <%= paginate @activities %>

    <%= content_tag :div, nil, id: 'story-modal', class: 'modal fade', tabindex: -1, role: 'dialog' %>

<% end %>